name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (without v prefix, e.g. 1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build binaries
    runs-on: ubuntu-latest
    needs: test  # Only build if tests pass
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64 # Go does not support windows/arm64 well for CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/pairstair-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          # Use a unique artifact name for each job (include the run attempt)
          name: pairstair-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: dist/pairstair-${{ matrix.goos }}-${{ matrix.goarch }}

  man-page:
    name: Build man page
    runs-on: ubuntu-latest
    needs: test  # Only build if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build man page
        run: |
          mkdir -p dist
          cd docs
          chmod +x gen-man.sh
          ./gen-man.sh
          cp pairstair.1 ../dist/

      - name: Upload man page
        uses: actions/upload-artifact@v4
        with:
          name: pairstair-man-page-${{ github.run_id }}-${{ github.run_attempt }}
          path: dist/pairstair.1

  release:
    name: Create GitHub Release
    needs: [test, build, man-page]  # Wait for all jobs including tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Get tag name
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "TAG_NAME=v${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: dist/**/*
          create_tag: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Trigger homebrew formula update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.HOMEBREW_UPDATE_TOKEN }}
          repository: gypsydave5/homebrew-pairstair
          event-type: pairstair-release
          client-payload: '{"version": "${{ env.VERSION }}"}'
